modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/BGSDT/yunzhu-yunbei-urban-construction/issues"
license = "MIT"

[[mods]]
modId = "yunbeiuc"
version = "${version}"
displayName = "Yunbei Urban Construction"
authors = "北咕, jstxjf_, 潇湘-迷蝎, Tizhengxie, NanGuaQWQ, Yomi_307, FrostyHulan"
logoFile = "icon.png"
description = '''
Yunbei Urban Construction - Yunzhu Workshop reduced build (municipal facilities only).
Ported & trimmed by DeepSeek V4.1; mod verification by Beigu.
'''

[[dependencies.yunbeiuc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yunbeiuc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.yunbeiuc]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
